### ISSUE TITLE
W3C - Our Staff: 40 Errors found.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Apollo-Health#24]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fapollohealth.stage.titanweb.com.au%2Four-staff%2F

**Comment by maehtitan** [comment]
5 Errors left

**Comment by euveng** [comment]
Fixed.

**Comment by maehtitan** [comment]
This page has not only 1 error, still have another 2 issues with this errors ": No p element in scope but a p end tag seen."

**Comment by euveng** [comment]
Fixed.
