### ISSUE TITLE
Search: Result title was set to h1. Only the page title should be set to h1 heading

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Apollo-Health#6]
![image](https://cloud.githubusercontent.com/assets/12888048/13596083/15f206fc-e54b-11e5-9a2a-cf9034f3772c.png)

**Comment by euveng** [comment]
Fixed.

**Comment by romatitan** [comment]
Not yet fixed.

@euveng 
**Note:** 
Kindly add a "fixed" label if the ticket is already resolved.
It will be a big help to identify which ticket/s is already fixed by the dev.
Thanks.

**Comment by jonathanza** [comment]
Fixed. Changed titles to 'h2'.
